routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\BrandController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\AttributeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('admin-panel/dashboard', function () {
    return view('admin.dashboard');
})->name('dashboard');

Route::get('/',function ()
{
    return redirect()->route('dashboard');
});

Route::prefix('admin-panel/management')->name('admin.')->group(function () {
    Route::resource('brands', BrandController::class);
    Route::resource('attributes', AttributeController::class);
    Route::resource('categories', CategoryController::class);
    Route::resource('tags', TagController::class);
    Route::resource('products', ProductController::class);
    Route::get('/category-attributes/{category}',[CategoryController::class,'getCategoryAttributes']);

});

resources/views/admin/sections/errors.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul class="mb-0">
            @foreach ($errors->all() as $error)
                <li class="alert-text">{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/admin/sections/footer.blade.php
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; WebProg.ir 1399</span>
        </div>
    </div>
</footer>

resources/views/admin/sections/scroll_top.blade.php
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

resources/views/admin/sections/sidebar.blade.php
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion pr-0" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Nezam Alinazari</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{{ route('dashboard') }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span> داشبورد </span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        فروشگاه
    </div>

    <!-- Nav Item - Brands Menu -->
    <li class="nav-item">
        <a class="nav-link" href="{{ route('admin.brands.index') }}" >
            <i class="fas fa-fw fa-store-slash"></i>
            <span>  برندها </span>
        </a>
    </li>

<!-- Nav Item - Market Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapseProducts" aria-expanded="true" aria-controls="collapseProducts">
          <i class="fas fa-fw fa-cart-plus"></i>
          <span> محصولات </span>
        </a>
        <div id="collapseProducts" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar" style="">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="{{ route('admin.attributes.index') }}">ویژگی ها</a>
            <a class="collapse-item" href="{{ route('admin.categories.index') }}">دسته بندی ها</a>
            <a class="collapse-item" href="{{ route('admin.tags.index') }}">تگ ها</a>
          </div>
        </div>
      </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>

resources/views/admin/sections/topbar.blade.php
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle">
        <i class="fa fa-bars" style="margin-top: 4px;"></i>
    </button>

    <!-- Topbar Search -->
    <form class="d-none d-sm-inline-block form-inline ml-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small order-2"
                placeholder="جستجو ..." aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav mr-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small order-2"
                            placeholder="جستجو ..." aria-label="Search" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Nav Item - Alerts -->
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">3+</span>
            </a>
            <!-- Dropdown - Alerts -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in text-right"
                aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                    لورم ایپسوم
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div>
                        <div class="small text-gray-500"> مهر 12, 1399 </div>
                        <span class="font-weight-bold"> متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و
                            با استفاده از طراحان
                            گرافیک است </span>
                    </div>

                    <div class="mr-3">
                        <div class="icon-circle bg-primary">
                            <i class="fas fa-file-alt text-white"></i>
                        </div>
                    </div>

                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">

                    <div>
                        <div class="small text-gray-500"> مهر 12, 1399 </div>
                        متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده
                    </div>

                    <div class="mr-3">
                        <div class="icon-circle bg-success">
                            <i class="fas fa-donate text-white"></i>
                        </div>
                    </div>

                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">

                    <div>
                        <div class="small text-gray-500"> مهر 12, 1399 </div>
                        متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ
                    </div>

                    <div class="mr-3">
                        <div class="icon-circle bg-warning">
                            <i class="fas fa-exclamation-triangle text-white"></i>
                        </div>
                    </div>

                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#"> مشاهده تمام </a>
            </div>
        </li>

        <!-- Nav Item - Messages -->
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>
                <!-- Counter - Messages -->
                <span class="badge badge-danger badge-counter">7</span>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in text-right"
                aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                    کامنت ها
                </h6>
                <a class="dropdown-item d-flex align-items-center justify-content-between" href="#">

                    <div class="font-weight-bold">
                        <div class="text-truncate">
                            متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک
                            است
                        </div>
                        <div class="small text-gray-500"> لورم ایپسوم </div>
                    </div>

                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60"
                            alt="">
                        <div class="status-indicator bg-success"></div>
                    </div>

                </a>
                <a class="dropdown-item d-flex align-items-center justify-content-between" href="#">

                    <div>
                        <div class="text-truncate">
                            متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک
                            است
                        </div>
                        <div class="small text-gray-500"> لورم ایپسوم </div>
                    </div>

                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60"
                            alt="">
                        <div class="status-indicator"></div>
                    </div>

                </a>
                <a class="dropdown-item d-flex align-items-center justify-content-between" href="#">

                    <div>
                        <div class="text-truncate">
                            متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک
                            است
                        </div>
                        <div class="small text-gray-500"> لورم ایپسوم </div>
                    </div>

                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60"
                            alt="">
                        <div class="status-indicator bg-warning"></div>
                    </div>

                </a>
                <a class="dropdown-item d-flex align-items-center justify-content-between" href="#">

                    <div>
                        <div class="text-truncate">
                            متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک
                            است
                        </div>
                        <div class="small text-gray-500"> لورم ایپسوم </div>
                    </div>

                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60"
                            alt="">
                        <div class="status-indicator bg-success"></div>
                    </div>

                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#"> مشاهده تمام کامنت ها
                </a>
            </div>
        </li>

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="ml-2 d-none d-lg-inline text-gray-600 small"> علی شیخ </span>
                <img class="img-profile rounded-circle" src="./img/user.jpg">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in text-right"
                aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                    <i class="fas fa-user fa-sm fa-fw ml-2 text-gray-400"></i>
                    پروفایل
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-cogs fa-sm fa-fw ml-2 text-gray-400"></i>
                    تنظیمات
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw ml-2 text-gray-400"></i>
                    خروج
                </a>
            </div>
        </li>

    </ul>

</nav>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
aria-hidden="true">
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel"> لورم ایپسوم متن ساختگی </h5>
            <button class="close ml-0" type="button" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
        </div>
        <div class="modal-body"> لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از
            طراحان گرافیک
            است. </div>
        <div class="modal-footer">
            <a class="btn btn-primary" href="login.html"> خروج </a>
            <button class="btn btn-secondary" type="button" data-dismiss="modal"> لغو </button>
        </div>
    </div>
</div>
</div>