routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\BrandController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\AttributeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('admin-panel/dashboard', function () {
    return view('admin.dashboard');
})->name('dashboard');

Route::get('/',function ()
{
    return redirect()->route('dashboard');
});

Route::prefix('admin-panel/management')->name('admin.')->group(function () {
    Route::resource('brands', BrandController::class);
    Route::resource('attributes', AttributeController::class);
    Route::resource('categories', CategoryController::class);
    Route::resource('tags', TagController::class);
    Route::resource('products', ProductController::class);
    Route::get('/category-attributes/{category}',[CategoryController::class,'getCategoryAttributes']);

});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $table='products';
    protected $guarded=[];
    
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Tag;
use App\Models\Brand;
use App\Models\Product;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $brands=Brand::all();
        $tags=Tag::all();
        $categories=Category::where('parent_id','!=',0)->get();

        return view('admin.products.create',compact('brands','tags','categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        dd($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        //
    }

}

resources/views/admin/products/create.blade.php
@extends('admin.layouts.admin')

@section('title')
    Create Product
@endsection

@section('content')
    <div class="row">
        <div class="col mb-4 p-md-5 bg-white">
            <div class="mb-4">
                <h5 class="font-weight-bold">ایجاد محصول</h5>
            </div>
            <hr>
            @include('admin.sections.errors')
            <form action="{{ route('admin.products.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="form-row">
                    <div class="form-group col-md-3">
                        <label for="name">نام</label>
                        <input class="form-control" type="text" name="name" id="name" value="{{ old('name') }}">
                    </div>
                    <div class="form-group col-md-3">
                        <label for="brandSelect">برند</label>
                        <select class="form-control" name="brandSelect" id="brandSelect" title="انتخاب برند">
                            @foreach ($brands as $brand)
                                <option value="{{ $brand->id }}">{{ $brand->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="is_active">وضعیت</label>
                        <select class="form-control" name="is_active" id="is_active">
                            <option value="0">غیرفعال</option>
                            <option selected value="1">فعال</option>
                        </select>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="tagsSelect">تگ</label>
                        <select class="form-control" name="tagsSelect[]" id="tagsSelect" multiple data-actions-box="true"
                            data-live-search="true" title="انتخاب تگ">
                            @foreach ($tags as $tag)
                                <option value="{{ $tag->id }}">{{ $tag->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group col-md-12">
                        <label for="description">توضیحات</label>
                        <textarea class="form-control" name="description" id="description">{!! old('description') !!}"</textarea>
                    </div>

                    {{-- Product Image Section --}}
                    <div class="col-md-12">
                        <hr>
                        <p class="font-weight-bold">
                            تصاویر محصول:
                        </p>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="primary_image">انتخاب تصویر اصلی</label>
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="primary_image" name="primary_image">
                            <label class="custom-file-label" for="primary_image">انتخاب فایل</label>
                        </div>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="images">انتخاب تصاویر </label>
                        <div class="custom-file">
                            <input type="file" multiple class="custom-file-input" id="images" name="images[]">
                            <label class="custom-file-label" for="images">انتخاب فایل ها</label>
                        </div>
                    </div>

                    {{-- Categories and attributes Section --}}
                    <div class="col-md-12">
                        <hr>
                        <p class="font-weight-bold">
                            دسته بندی و ویژگی ها:
                        </p>
                    </div>

                    <div class="col-md-12">
                        <div class="row justify-content-center">
                            <div class="form-group  col-md-3">
                                <label for="categorySelect">دسته بندی</label>
                                <select class="form-control" name="categorySelect" id="categorySelect"
                                    data-live-search="true" title="انتخاب دسته بندی">
                                    @foreach ($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->name }}-
                                            {{ $category->parent->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>

                    <div id="attributesContainer" class="col-md-12">
                        <div id="attributes" class="row">

                        </div>
                        <div class="col-md-12">
                            <hr>
                            <p>
                                افزودن قیمت و موجودی برای متغیر <span class="font-weight-bold" id="variationName"></span>:
                            </p>
                        </div>
                        <div id="czContainer">
                            <div id="first">
                                <div class="recordset">
                                    <div class="row">
                                        <div class="form-group col-md-3">
                                            <label>نام</label>
                                            <input class="form-control" type="text" name="variation[value][]">
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label>قیمت</label>
                                            <input class="form-control" type="text" name="variation[price][]">
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label>تعداد</label>
                                            <input class="form-control" type="text" name="variation[quantity][]">
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label>شناسه انبار</label>
                                            <input class="form-control" type="text" name="variation[sku][]">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                     {{-- Delivery Section --}}
                     <div class="col-md-12">
                        <hr>
                        <p class="font-weight-bold">
                            هزینه ارسال:
                        </p>
                    </div>

                    <div class="form-group col-md-3">
                        <label for="delivery_amount">هزینه ارسال</label>
                        <input class="form-control" type="text" name="delivery_amount" id="delivery_amount" value="{{ old('delivery_amount')}}">
                    </div>

                    <div class="form-group col-md-3">
                        <label for="delivery_amount_per_product">هزینه ارسال به ازای محصول اضافی</label>
                        <input class="form-control" type="text" name="delivery_amount_per_product" id="delivery_amount_per_product" value="{{ old('delivery_amount_per_product')}}">
                    </div>


                </div>


                <!-- The elements you want repeated must be wrapped in an element with id="recordset" -->

                {{-- <div class="form-group col-md-3">
                        <label for="attributeSelect">ویژگی ها</label>
                        <select id="attributeSelect" class="form-control" name="attribute_ids[]" data-actions-box="true"
                            multiple data-live-search="true" title="انتخاب ویژگی">
                            @foreach ($attributes as $attribute)
                                <option value="{{ $attribute->id }}">{{ $attribute->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="attributeIsFilterSelect">انتخاب ویژگی های قابل فیلتر</label>
                        <select id="attributeIsFilterSelect" class="form-control" name="attribute_is_filter_ids[]"
                            data-actions-box="true" multiple data-live-search="true" title="انتخاب ویژگی">

                        </select>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="variationSelect">انتخاب ویژگی متغیر</label>
                        <select id="variationSelect" class="form-control" name="variation_id" data-live-search="true"
                            title="انتخاب ویژگی">

                        </select>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="icon">آیکون</label>
                        <input class="form-control" type="text" name="icon" id="icon" value="{{ old('icon') }}">
                    </div> --}}



                <button class="btn btn-outline-primary mt-5" type="submit">ثبت</button>
                <a class="btn btn-dark mt-5 mr-3" href="{{ route('admin.products.index') }}"><i
                        class="fa fa-fw fa-chevron-left"></i>بازگشت</a>
            </form>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $('#tagsSelect').selectpicker();
        $('#brandSelect').selectpicker();
        $('#primary_image').change(function() {

            var fileName = $(this).val();
            $(this).next('.custom-file-label').html(fileName);
        });
        $('#images').change(function() {

            var fileName = $(this).val();
            $(this).next('.custom-file-label').html(fileName);
        });
        $('#categorySelect').selectpicker();
        $('#attributesContainer').hide();
        $('#categorySelect').change(function() {

            let categorySelected = $(this).val();
            axios.get(`{{ url('/admin-panel/management/category-attributes/${categorySelected}') }}`)
                .then(function(response) {

                    $('#attributesContainer').fadeIn();
                    $('#attributes').empty();

                    response.data.attributes.forEach((element) => {
                        let attributeElement = $('<div/>', {
                            class: 'form-group col-md-3'
                        }).append($('<label/>', {
                            for: `attributes[${element.id}]`,
                            text: element.name
                        })).append($('<input/>', {
                            class: 'form-control',
                            type: 'text',
                            id: `attributes[${element.id}]`,
                            name: `attributes[${element.id}]`
                        }));

                        $("#attributes").append(attributeElement);

                    });

                    $('#variationName').text(response.data.variation.name);


                    console.log(response.data);
                })
                .catch(function(error) {
                    console.log(error);
                });

        });
        $("#czContainer").czMore();
    </script>
@endsection

resources/views/admin/products/edit.blade.php
@extends('admin.layouts.admin')

@section('title')
    Edit Category
@endsection

@section('content')
    <div class="row">
        <div class="col mb-4 p-md-5 bg-white">
            <div class="mb-4">
                <h5 class="font-weight-bold">ویرایش دسته بندی <strong class="text-warning">{{ $category->name }}</strong>
                </h5>
            </div>
            <hr>
            @include('admin.sections.errors')
            <form action="{{ route('admin.categories.update', ['category' => $category->id]) }}" method="post">
                @csrf
                @method('put')
                <div class="form-row">
                    <div class="form-group col-md-3">
                        <label for="name">نام</label>
                        <input class="form-control" type="text" name="name" id="name" value="{{ $category->name }}">
                    </div>
                    <div class="form-group col-md-3">
                        <label for="slug">نام انگلیسی</label>
                        <input class="form-control" type="text" name="slug" id="slug" value="{{ $category->slug }}">
                    </div>
                    <div class="form-group col-md-3">
                        <label for="parent_id">والد</label>
                        <select class="form-control" name="parent_id" id="parent_id">
                            <option value="0">بدون والد</option>
                            @foreach ($parentCategories as $parentCategory)
                                <option value="{{ $parentCategory->id }}"
                                    {{ $category->parent_id == $parentCategory->id ? 'selected' : '' }}>
                                    {{ $parentCategory->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="is_active">وضعیت</label>
                        <select class="form-control" name="is_active" id="is_active">
                            <option {{ $category->is_active == 'غیرفعال' ? '' : 'selected' }} value="0">غیرفعال</option>
                            <option {{ $category->is_active == 'فعال' ? 'selected' : '' }} value="1">فعال</option>
                        </select>
                    </div>
                    <div class="form-group col-md-3">

                        <label for="attributeSelect">ویژگی ها</label>
                        <select id="attributeSelect" class="form-control" name="attribute_ids[]" data-actions-box="true"
                            multiple data-live-search="true" title="انتخاب ویژگی">
                            @foreach ($attributes as $attribute)
                                <option value="{{ $attribute->id }}" {{-- {{ $category->attributes()->wherePivot('attribute_id', $attribute->id)->first()
                                        ? 'selected'
                                        : '' }} --}}
                                    {{ in_array($attribute->id,$category->attributes()->pluck('id')->toArray())? 'selected': '' }}>
                                    {{ $attribute->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="attributeIsFilterSelect">انتخاب ویژگی های قابل فیلتر</label>
                        <select id="attributeIsFilterSelect" class="form-control" name="attribute_is_filter_ids[]"
                            data-actions-box="true" multiple data-live-search="true" title="انتخاب ویژگی">
                            @forelse ($category->attributes()->wherePivot('is_filter', 1)->get() as $attribute )
                            <option value="{{ $attribute->id }}"
                                selected>{{ $attribute->name }}</option>
                            @empty

                            @endforelse()


                        </select>
                    </div>

                    <div class="form-group col-md-3">
                        <label for="variationSelect">انتخاب ویژگی متغیر</label>
                        <select id="variationSelect" class="form-control" name="variation_id" data-live-search="true"
                            title="انتخاب ویژگی">
                            <option value="{{ $category->attributes()->wherePivot('is_variation',1)->first()->id??'' }}" selected>{{ $category->attributes()->wherePivot('is_variation',1)->first()->name??'' }}</option>
                        </select>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="icon">آیکون</label>
                        <input class="form-control" type="text" name="icon" id="icon" value="{{ $category->icon }}">
                    </div>
                    <div class="form-group col-md-12">
                        <label for="description">توضیحات</label>
                        <textarea class="form-control" name="description" id="description">{{ $category->description }}"</textarea>
                    </div>



                </div>


                <button class="btn btn-outline-success mt-5" type="submit"> <i class="fa fa-fw fa-save"></i>ویرایش</button>
                <a class="btn btn-dark mt-5 mr-3" href="{{ route('admin.categories.index') }}"><i
                        class="fa fa-fw fa-chevron-left"></i> بازگشت</a>
            </form>

        </div>
    </div>
@endsection


@section('script')
    <script>
        $('#attributeSelect').selectpicker();
        $('#attributeIsFilterSelect').selectpicker();
        $('#variationSelect').selectpicker();

        $('#attributeSelect').change(function() {
            let attributesSelected = $(this).val();
            let attributes = @json($attributes);

            let attributeForFilter = [];

            attributes.map((attribute) => {
                $.each(attributesSelected, function(i, element) {
                    if (attribute.id == element) {
                        attributeForFilter.push(attribute);
                    }
                });
            });

            $("#attributeIsFilterSelect").find("option").remove();
            $("#variationSelect").find("option").remove();
            attributeForFilter.forEach((element) => {
                let attributeFilterOption = $("<option/>", {
                    value: element.id,
                    text: element.name
                });

                let variationOption = $("<option/>", {
                    value: element.id,
                    text: element.name
                });

                $("#attributeIsFilterSelect").append(attributeFilterOption);
                $("#attributeIsFilterSelect").selectpicker('refresh');

                $("#variationSelect").append(variationOption);
                $("#variationSelect").selectpicker('refresh');
            });
        });
    </script>
@endsection

resources/views/admin/products/index.blade.php
@extends('admin.layouts.admin')

@section('title')
    Index Category
@endsection

@section('content')
    <div class="row">
        <div class="col mb-4 p-md-5 bg-white">
            <div class="d-flex mb-5 justify-content-between">
                <h5 class="font-weight-bold">لیست دسته بندی ها ({{ $categories->total() }})</h5>
                <a class="btn btn-outline-primary" href="{{ route('admin.categories.create') }}">
                    <i class="fa fa-plus"></i>
                    ایجاد دسته بندی
                </a>
            </div>
           <div>
            <hr>
           </div>
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">نام</th>
                        <th scope="col">نام انگلیسی</th>
                        <th scope="col">والد</th>
                        <th scope="col">وضعیت</th>
                        <th scope="col">عملیات</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach ($categories as $key => $category)
                        <tr>
                            <th scope="row">{{ $categories->firstItem() + $key }}</th>
                            <td>{{ $category->name }}</td>
                            <td>{{ $category->slug }}</td>
                            <td>
                                @if ($category->parent_id == 0)
                                    {{ 'بدون والد' }}
                                @else
                                    {{ $category->parent->name }}
                                @endif
                            </td>
                            <td class="{{ $category->getRawOriginal('is_active') ? 'text-success' : 'text-danger' }}">
                                {{ $category->is_active }}</td>
                            <td class="col-md-auto">
                                <a class="btn btn-outline-primary"
                                    href="{{ route('admin.categories.show', ['category' => $category->id]) }}">
                                    <li class="fa fa-eye"></li>
                                    نمایش
                                </a>
                                <a class="btn btn-outline-success"
                                    href="{{ route('admin.categories.edit', ['category' => $category->id]) }}">
                                    <i class="fa fa-edit"></i>
                                    ویرایش
                                </a>
                            </td>
                        </tr>
                    @endforeach

                </tbody>
            </table>
            {{ $categories->links() }}
        </div>
    </div>
@endsection

resources/views/admin/products/show.blade.php
@extends('admin.layouts.admin')

@section('title')
    Show Category
@endsection

@section('content')
    <div class="row">
        <div class="col mb-4 p-md-5 bg-white">
            <div class="mb-4">
                <h5 class="font-weight-bold">نمایش دسته بندی</h5>
            </div>
            <hr>

            <div class="row">
                <div class="form-group col-md-3">
                    <label>نام</label>
                    <input class="form-control" type="text" disabled value="{{ $category->name }}">
                </div>
                <div class="form-group col-md-3">
                    <label>نام انگلیسی</label>
                    <input class="form-control" type="text" disabled value="{{ $category->slug }}">
                </div>
                <div class="form-group col-md-3">
                    <label>والد</label>
                    <input class="form-control" type="text" disabled
                        value=" @if ($category->parent_id == 0) {{ 'بدون والد' }}
                        @else
                         {{ $category->parent->name }} @endif">
                </div>
                <div class="form-group col-md-3">
                    <label>وضعیت</label>
                    <input class="form-control" type="text" disabled value="{{ $category->is_active }}">
                </div>
                <div class="form-group col-md-3">
                    <label> ایکون</label>
                    <input class="form-control" type="text" disabled value="{{ $category->icon }}">
                </div>
                <div class="form-group col-md-3">
                    <label>تاریخ ایجاد</label>
                    <input class="form-control" type="text" disabled value="{{ verta($category->created_at) }}">
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-3">
                    <label>ویژگی ها</label>
                    <div class="form-control disabled">
                        @foreach ($category->attributes as $attribute)
                            {{ $attribute->name }} {{ $loop->last ? '' : ',' }}
                        @endforeach
                    </div>
                </div>
                <div class="col-md-3">
                    <label>ویژگی های قابل فیلتر</label>
                    <div class="form-control disabled">
                        @foreach ($category->attributes()->wherePivot('is_filter',1)->get() as $attribute)
                            {{ $attribute->name }} {{ $loop->last ? '' : ',' }}
                        @endforeach
                    </div>
                </div>
                <div class="col-md-3">
                    <label>ویژگی متغیر</label>
                    <div class="form-control disabled">
                        @foreach ($category->attributes()->wherePivot('is_variation',1)->get() as $attribute)
                            {{ $attribute->name }} {{ $loop->last ? '' : ',' }}
                        @endforeach
                    </div>
                </div>
            </div>

            <a class="btn btn-dark mt-5" href="{{ route('admin.categories.index') }}"><i
                    class="fa fa-fw fa-chevron-left"></i>
                بازگشت</a>

        </div>
    </div>
@endsection