routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\BrandController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\AttributeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('admin-panel/dashboard', function () {
    return view('admin.dashboard');
})->name('dashboard');

Route::get('/',function ()
{
    return redirect()->route('dashboard');
});

Route::prefix('admin-panel/management')->name('admin.')->group(function () {
    Route::resource('brands', BrandController::class);
    Route::resource('attributes', AttributeController::class);
    Route::resource('categories', CategoryController::class);
    Route::resource('tags', TagController::class);
    Route::resource('products', ProductController::class);
    Route::get('/category-attributes/{category}',[CategoryController::class,'getCategoryAttributes']);

});

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;

    protected $fillable=['name'];
    protected $table='tags';
}

app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Tag;
use Illuminate\Http\Request;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags=Tag::latest()->paginate(20);
        return view('admin.tags.index',compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required'
        ]);

        Tag::create([
            'name'=>$request->name
        ]);

        alert()->success('تگ مورد نظر با موفقیت ثبت شد','با تشکر');

        return redirect()->route('admin.tags.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function show(Tag $tag)
    {
        return view('admin.tags.show',compact('tag'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        return view('admin.tags.edit', compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tag $tag)
    {
        $request->validate([
            'name'=>'required'
        ]);

        $tag->update([
            'name'=>$request->name
        ]);

        alert()->success('تگ مورد نظر با موفقیت ویراش شد','با تشکر');
        return redirect()->route('admin.tags.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        $tag->delete();
        alert()->warning('تگ مورد نظر با موفقیت حذف گردید','توجه');
        return redirect()->back();

    }
}

resources/views/admin/tags/create.blade.php
@extends('admin.layouts.admin')

@section('title')
 Create Tag
@endsection

@section('content')

<div class="row">
    <div class="col mb-4 p-md-5 bg-white">
        <div class="mb-4">
            <h5 class="font-weight-bold">ایجاد تگ</h5>
        </div>
        <hr>
        @include('admin.sections.errors')
        <form action="{{ route('admin.tags.store') }}" method="post">
            @csrf
           <div class="form-row">
            <div class="form-group col-md-3">
                <label for="name">نام</label>
                <input class="form-control" type="text" name="name" id="name">
            </div>
           </div>
           <button class="btn btn-outline-primary mt-5" type="submit"><i class="fa fa-fw fa-save"></i> ثبت</button>
           <a class="btn btn-dark mt-5 mr-3" href="{{ route('admin.tags.index') }}"><i class="fa fa-fw fa-chevron-left"></i>بازگشت</a>
        </form>

    </div>
</div>
@endsection

resources/views/admin/tags/edit.blade.php
@extends('admin.layouts.admin')

@section('title')
    Edit Tag
@endsection

@section('content')
    <div class="row">
        <div class="col mb-4 p-md-5 bg-white">
            <div class="mb-4">
                <h5 class="font-weight-bold">ویرایش تگ <strong class="text-warning">{{ $tag->name }}</strong></h5>
            </div>
            <hr>
            @include('admin.sections.errors')
            <form action="{{ route('admin.tags.update', ['tag' => $tag->id]) }}" method="post">
                @csrf
                @method('put')
                <div class="form-row">
                    <div class="form-group col-md-3">
                        <label for="name">نام</label>
                        <input class="form-control" type="text" name="name" id="name" value="{{ $tag->name }}">
                    </div>
                </div>

                <button class="btn btn-outline-success mt-5" type="submit"> <i class="fa fa-fw fa-save"></i>تأیید</button>
                <a class="btn btn-dark mt-5 mr-3" href="{{ route('admin.tags.index') }}"><i
                        class="fa fa-fw fa-chevron-left"></i> بازگشت</a>
            </form>

        </div>
    </div>
@endsection

resources/views/admin/tags/index.blade.php
@extends('admin.layouts.admin')

@section('title')
    Index Tag
@endsection

@section('content')
    <div class="row">
        <div class="col mb-4 p-md-5 bg-white">
            <div class="d-flex mb-5 justify-content-between">
                <h5 class="font-weight-bold">لیست تگ ها ({{ $tags->total() }})</h5>
                <a class="btn btn-outline-primary" href="{{ route('admin.tags.create') }}">
                    <i class="fa fa-plus"></i>
                    ایجاد تگ
                </a>
            </div>
            <hr>
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th scope="col">ردیف</th>
                        <th scope="col">نام تگ</th>
                        <th scope="col">عملیات</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach ($tags as $key => $tag)
                        <tr>
                            <th scope="row">{{ $tags->firstItem() + $key }}</th>
                            <td>{{ $tag->name }}</td>
                            <td class="col-md-auto">
                                <a class="btn btn-outline-primary"
                                    href="{{ route('admin.tags.show', ['tag' => $tag->id]) }}">
                                    <li class="fa fa-eye"></li>
                                    نمایش
                                </a>
                                <a class="btn btn-outline-success"
                                    href="{{ route('admin.tags.edit', ['tag' => $tag->id]) }}">
                                    <i class="fa fa-edit"></i>
                                    ویرایش
                                </a>
                                <form action="{{ route('admin.tags.destroy', ['tag' => $tag->id]) }}" method="post"
                                    class="d-inline-block">
                                    @csrf
                                    @method('delete')
                                    <button class="btn btn-outline-danger" type="submit"> <i class="fa fa-fw fa-recycle "></i>حذف</button>

                                </form>
                            </td>
                        </tr>
                    @endforeach

                </tbody>
            </table>
            {{ $tags->links() }}
        </div>
    </div>
@endsection

resources/views/admin/tags/show.blade.php
@extends('admin.layouts.admin')

@section('title')
    Show Tag
@endsection

@section('content')
    <div class="row">
        <div class="col mb-4 p-md-5 bg-white">
            <div class="mb-4">
                <h5 class="font-weight-bold">نمایش تگ</h5>
            </div>
            <hr>

            <div class="row">
                <div class="form-group col-md-3">
                    <label>نام</label>
                    <input class="form-control" type="text" disabled value="{{ $tag->name }}">
                </div>
                <div class="form-group col-md-3">
                    <label>تاریخ ایجاد</label>
                    <input class="form-control" type="text" disabled value="{{ verta($tag->created_at) }}">
                </div>
            </div>

            <a class="btn btn-dark mt-5" href="{{ route('admin.tags.index') }}"><i class="fa fa-fw fa-chevron-left"></i>
                بازگشت</a>

        </div>
    </div>
@endsection